security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        App\Entity\User:         bcrypt
        App\Form\Model\UserData: bcrypt

    providers:
        user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true

            # this is enabled for unit tests
            http_basic: ~

            form_login:
                csrf_token_generator: security.csrf.token_manager
                check_path: login_check
                login_path: login

            logout:
                csrf_parameter: token
                csrf_token_generator: security.csrf.token_manager
                path: log_out

            remember_me:
                secret: "%env(APP_SECRET)%"
                always_remember_me: true

            user_checker: App\Security\UserChecker

    role_hierarchy:
        ROLE_ADMIN:        [ROLE_TRUSTED_USER, ROLE_USER]
        ROLE_TRUSTED_USER: [ROLE_USER]
