message_list:
    controller: App\Controller\MessageController::list
    defaults: { page: 1 }
    path: /messages/{page}
    methods: [GET]
    requirements: { page: \d+ }

message:
    controller: App\Controller\MessageController::message
    path: /message/{id}
    methods: [GET]
    requirements: { id: "%number_regex%" }

compose_message:
    controller: App\Controller\MessageController::compose
    path: /compose_message/{username}
    methods: [GET, POST]
    requirements: { username: \w+ }

reply_to_message:
    controller: App\Controller\MessageController::reply
    path: /message_reply/{id}
    methods: [POST]
    requirements: { id: "%number_regex%" }
