search:
    controller: App\Controller\SearchController::search
    path: /search
    methods: [GET]

external_search:
    controller: App\Controller\SearchController::external
    path: /external_search
    methods: [POST]
